DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS features;
DROP TABLE IF EXISTS styles CASCADE;
DROP TABLE IF EXISTS related_products;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS skus;